from django.db import models


class Skill(models.Model):

    name = models.CharField(max_length=50, blank=True)
    system = models.CharField(max_length=10, blank=True)
    power = models.IntegerField(default=0)


class Pokemon(models.Model):

    name = models.CharField(max_length=50, blank=True)
    no = models.IntegerField(default=0)
    system = models.CharField(max_length=20, blank=True)
    default_skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    attack = models.IntegerField(default=0)
    defense = models.IntegerField(default=0)
    hp = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    evo_to = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE)
    pic = models.ImageField(upload_to='pokemon', null=True, blank=True)


class Player(models.Model):

    name = models.CharField(max_length=50, blank=True)
    is_ai = models.BooleanField(default=False)


class Card(models.Model):

    STATUS_CHOICES = (
        (-1, '弃牌'),
        (0, '牌堆'),
        (1, '手牌'),
        (2, '休养'),
        (3, '上场'),
    )

    player = models.ForeignKey(Player, null=True, blank=True, on_delete=models.CASCADE)
    pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE)
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    level = models.IntegerField(default=1)

    @property
    def systems(self):
        return self.pokemon.system.split('/')

    @property
    def attack(self):
        extra_points = self.extrapoint_set.filter(kind='attack').count()
        return self.pokemon.attack + extra_points

    @property
    def defense(self):
        extra_points = self.extrapoint_set.filter(kind='defense').count()
        return self.pokemon.attack + extra_points

    @property
    def hp(self):
        extra_points = self.extrapoint_set.filter(kind='hp').count()
        return self.pokemon.attack + extra_points

    @property
    def effective_points(self):
        return self.extrapoint_set.all().count()

    @property
    def available_points(self):
        return self.level - self.pokemon.level - self.effective_points


class ExtraPoint(models.Model):

    KIND_CHOICES = (
        ('attack', 'attack'),
        ('defense', 'defense'),
        ('hp', 'hp'),
    )

    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    kind = models.CharField(max_length=20, choices=KIND_CHOICES, default='attack')


def pokemon_init():
    skills = [{'name': '藤鞭', 'power': 40, 'system': '草'},
              {'name': '水蛭种子', 'power': 50, 'system': '草'},
              {'name': '飞叶快刀', 'power': 85, 'system': '草'},
              {'name': '叶片剪', 'power': 70, 'system': '草'},
              {'name': '吸收', 'power': 40, 'system': '草'},
              {'name': '阳光烈焰', 'power': 90, 'system': '草'},
              {'name': '生长', 'power': 80, 'system': '草'},
              {'name': '植物', 'power': 60, 'system': '草'},
              {'name': '灰烬', 'power': 55, 'system': '火'},
              {'name': '喷射火焰', 'power': 70, 'system': '火'},
              {'name': '大字火', 'power': 95, 'system': '火'},
              {'name': '大字爆', 'power': 100, 'system': '火'},
              {'name': '水枪', 'power': 40, 'system': '水'},
              {'name': '泡沫', 'power': 65, 'system': '水'},
              {'name': '水炮', 'power': 100, 'system': '水'},
              {'name': '水泡兵', 'power': 70, 'system': '水'},
              {'name': '浪击', 'power': 90, 'system': '水'},
              {'name': '巴巴', 'power': 80, 'system': '水'},
              {'name': '连续切', 'power': 30, 'system': '虫'},
              {'name': '毒角刺', 'power': 20, 'system': '毒'},
              {'name': '啄击', 'power': 40, 'system': '飞'},
              {'name': '飞击', 'power': 90, 'system': '飞'},
              {'name': '教练啄食', 'power': 50, 'system': '飞'},
              {'name': '翅膀攻击', 'power': 75, 'system': '飞'},
              {'name': '缠绕', 'power': 15, 'system': '地'},
              {'name': '紧紧缠绕', 'power': 25, 'system': '地'},
              {'name': '双飞踢', 'power': 50, 'system': '地'},
              {'name': '连飞踢', 'power': 70, 'system': '地'},
              {'name': '狂暴攻击', 'power': 90, 'system': '地'},
              {'name': '挖攻', 'power': 50, 'system': '地'},
              {'name': '地震', 'power': 100, 'system': '地'},
              {'name': '猛撞攻击', 'power': 75, 'system': '地'},
              {'name': '十万伏特', 'power': 60, 'system': '电'},
              {'name': '打雷攻击', 'power': 85, 'system': '电'},
              {'name': '雷电波', 'power': 50, 'system': '电'},
              {'name': '亿万伏特', 'power': 100, 'system': '电'},
              {'name': '破坏死光', 'power': 100, 'system': '超'},
              {'name': '漂亮', 'power': 75, 'system': '超'},
              {'name': '???', 'power': 100, 'system': '超'},
              {'name': '拳击', 'power': 70, 'system': '格'},
              {'name': '地球摔', 'power': 100, 'system': '格'},
              {'name': '力量', 'power': 30, 'system': '格'},
              {'name': '万吨拳击', 'power': 90, 'system': '格'},
              {'name': '连续踢', 'power': 60, 'system': '格'},
              {'name': '快拳', 'power': 75, 'system': '格'},
              {'name': '落石', 'power': 50, 'system': '岩'},
              {'name': '炸击', 'power': 150, 'system': '岩'},
              {'name': '倒下', 'power': 60, 'system': '岩'},
              {'name': '冰冻拳', 'power': 50, 'system': '冰'},
              {'name': '冰光线', 'power': 90, 'system': '冰'},
              {'name': '冷冻拳', 'power': 80, 'system': '冰'},
              {'name': '暴风雪', 'power': 100, 'system': '冰'},
              {'name': '夜阴影', 'power': 70, 'system': '鬼'},
              {'name': '梦中食人兽', 'power': 100, 'system': '鬼'},
              {'name': '龙愤怒', 'power': 75.0, 'system': '龙'},
              {'name': '龙之怒', 'power': 100, 'system': '龙'},
              {'name': '揪抓', 'power': 40, 'system': '普'},
              {'name': '疯狂乱抓', 'power': 50, 'system': '普'},
              {'name': '重击', 'power': 55, 'system': '普'},
              {'name': '连击', 'power': 50, 'system': '普'},
              {'name': '击杀', 'power': 40, 'system': '普'},
              {'name': '万吨拳击', 'power': 90, 'system': '普'},
              {'name': '万吨铁拳', 'power': 100, 'system': '普'},
              {'name': '电光一闪', 'power': 50, 'system': '普'},
              {'name': '藤鞭 ', 'power': 40, 'system': '草'},
              {'name': '灰烬 ', 'power': 55, 'system': '火'},
              {'name': '火焰喷射', 'power': 70, 'system': '火'},
              {'name': '大字火 ', 'power': 95, 'system': '火'},
              {'name': '水枪 ', 'power': 40, 'system': '水'},
              {'name': '水炮 ', 'power': 100, 'system': '水'},
              {'name': '啄击 ', 'power': 40, 'system': '飞'},
              {'name': '飞击  ', 'power': 90, 'system': '飞'},
              {'name': '揪抓 ', 'power': 40, 'system': '地'},
              {'name': '缠绕 ', 'power': 15, 'system': '毒'},
              {'name': '紧紧缠绕 ', 'power': 25, 'system': '毒'},
              {'name': '十万伏特 ', 'power': 60, 'system': '电'},
              {'name': '打雷攻击 ', 'power': 85, 'system': '电'},
              {'name': '挖攻 ', 'power': 50, 'system': '地'},
              {'name': '超级之星 ', 'power': 80, 'system': '地'},
              {'name': '楸抓 ', 'power': 40, 'system': '毒'},
              {'name': '双飞踢 ', 'power': 50, 'system': '毒'},
              {'name': '连飞踢 ', 'power': 70, 'system': '毒'},
              {'name': '毒角刺 ', 'power': 20, 'system': '毒'},
              {'name': '重击 ', 'power': 55, 'system': '普'},
              {'name': '连击 ', 'power': 50, 'system': '普'},
              {'name': '火焰喷射 ', 'power': 70, 'system': '火'},
              {'name': '大字爆 ', 'power': 100, 'system': '火'},
              {'name': '翅膀攻击 ', 'power': 75, 'system': '飞'},
              {'name': '吸收 ', 'power': 40, 'system': '草'},
              {'name': '叶片剪 ', 'power': 70, 'system': '草'},
              {'name': '阳光烈焰 ', 'power': 90, 'system': '草'},
              {'name': '击杀 ', 'power': 40, 'system': '虫'},
              {'name': '破坏死光 ', 'power': 100, 'system': '超'},
              {'name': '拳击 ', 'power': 70, 'system': '格'},
              {'name': '地球摔 ', 'power': 100, 'system': '格'},
              {'name': '水泡兵 ', 'power': 70, 'system': '水'},
              {'name': '浪击 ', 'power': 70, 'system': '水'},
              {'name': '漂亮 ', 'power': 75, 'system': '超'},
              {'name': '植物 ', 'power': 60, 'system': '草'},
              {'name': '落石 ', 'power': 50, 'system': '岩'},
              {'name': '炸击 ', 'power': 150, 'system': '岩'},
              {'name': '倒下 ', 'power': 60, 'system': '岩'},
              {'name': '雷电波 ', 'power': 50, 'system': '电'},
              {'name': '大葱切 ', 'power': 80, 'system': '飞'},
              {'name': '冰冻拳 ', 'power': 50, 'system': '水'},
              {'name': '冰光线 ', 'power': 90, 'system': '水'},
              {'name': '夜阴影 ', 'power': 70, 'system': '鬼'},
              {'name': '束紧 ', 'power': 35, 'system': '岩'},
              {'name': '泡沫 ', 'power': 65, 'system': '水'},
              {'name': '自爆 ', 'power': 110, 'system': '电'},
              {'name': '杀 ', 'power': 150, 'system': '电'},
              {'name': '连续踢 ', 'power': 60, 'system': '格'},
              {'name': '快拳 ', 'power': 75, 'system': '格'},
              {'name': '舔舌头 ', 'power': 55, 'system': '毒'},
              {'name': '地震 ', 'power': 100, 'system': '地'},
              {'name': '巴巴拉 ', 'power': 80, 'system': '水'},
              {'name': '连续切 ', 'power': 30, 'system': '虫'},
              {'name': '冷冻拳 ', 'power': 80, 'system': '冰'},
              {'name': '角作角撞攻击', 'power': 65, 'system': '虫'},
              {'name': '龙愤怒 ', 'power': 75.0, 'system': '龙'},
              {'name': '钢铁之翼', 'power': 100, 'system': '飞'},
              {'name': '暴风雪 ', 'power': 100, 'system': '冰'},
              {'name': '龙之怒 ', 'power': 100, 'system': '龙'},
              {'name': '??? ', 'power': 100, 'system': '超'}]
    pokemons = [{'attack': '45',
                 'defense': '50',
                 'hp': '55',
                 'name': '妙蛙种子',
                 'no': 1,
                 'skill_name': '藤鞭 ',
                 'system': '草'},
                {'attack': '80',
                 'defense': '90',
                 'hp': '100',
                 'name': '妙蛙草',
                 'no': 2,
                 'skill_name': '水蛭种子',
                 'system': '草'},
                {'attack': '150',
                 'defense': '150',
                 'hp': '180',
                 'name': '妙蛙花',
                 'no': 3,
                 'skill_name': '飞叶快刀',
                 'system': '草'},
                {'attack': '70',
                 'defense': '35',
                 'hp': '45',
                 'name': '小火龙',
                 'no': 4,
                 'skill_name': '灰烬 ',
                 'system': '火'},
                {'attack': '130',
                 'defense': '60',
                 'hp': '90',
                 'name': '火恐龙',
                 'no': 5,
                 'skill_name': '火焰喷射',
                 'system': '火'},
                {'attack': '210',
                 'defense': '110',
                 'hp': '170',
                 'name': '喷火龙',
                 'no': 6,
                 'skill_name': '大字火 ',
                 'system': '火'},
                {'attack': '40',
                 'defense': '75',
                 'hp': '60',
                 'name': '杰尼龟',
                 'no': 7,
                 'skill_name': '水枪 ',
                 'system': '水'},
                {'attack': '60',
                 'defense': '150',
                 'hp': '120',
                 'name': '卡咪龟',
                 'no': 8,
                 'skill_name': '',
                 'system': '水'},
                {'attack': '125',
                 'defense': '250',
                 'hp': '220',
                 'name': '水箭龟',
                 'no': 9,
                 'skill_name': '水炮 ',
                 'system': '水'},
                {'attack': '35',
                 'defense': '40',
                 'hp': '50',
                 'name': '绿毛虫',
                 'no': 10,
                 'skill_name': '',
                 'system': '虫'},
                {'attack': '25',
                 'defense': '135',
                 'hp': '200',
                 'name': '铁甲蛹',
                 'no': 11,
                 'skill_name': '',
                 'system': '虫'},
                {'attack': '130',
                 'defense': '100',
                 'hp': '175',
                 'name': '八大蝴',
                 'no': 12,
                 'skill_name': '',
                 'system': '虫/毒'},
                {'attack': '40',
                 'defense': '35',
                 'hp': '45',
                 'name': '独角虫',
                 'no': 13,
                 'skill_name': '',
                 'system': '虫/毒'},
                {'attack': '25',
                 'defense': '135',
                 'hp': '190',
                 'name': '铁壳昆',
                 'no': 14,
                 'skill_name': '',
                 'system': '虫/毒'},
                {'attack': '140',
                 'defense': '95',
                 'hp': '170',
                 'name': '大针蜂',
                 'no': 15,
                 'skill_name': '',
                 'system': '虫/毒'},
                {'attack': '45',
                 'defense': '45',
                 'hp': '50',
                 'name': '波波',
                 'no': 16,
                 'skill_name': '啄击 ',
                 'system': '飞'},
                {'attack': '80',
                 'defense': '80',
                 'hp': '95',
                 'name': '比比鸟',
                 'no': 17,
                 'skill_name': '',
                 'system': '飞'},
                {'attack': '150',
                 'defense': '140',
                 'hp': '185',
                 'name': '比雕',
                 'no': 18,
                 'skill_name': '飞击  ',
                 'system': '飞'},
                {'attack': '50',
                 'defense': '40',
                 'hp': '45',
                 'name': '小拉达',
                 'no': 19,
                 'skill_name': '揪抓 ',
                 'system': '地'},
                {'attack': '130',
                 'defense': '130',
                 'hp': '175',
                 'name': '拉达',
                 'no': 20,
                 'skill_name': '',
                 'system': '地'},
                {'attack': '50',
                 'defense': '40',
                 'hp': '45',
                 'name': '烈雀',
                 'no': 21,
                 'skill_name': '啄击 ',
                 'system': '飞'},
                {'attack': '150',
                 'defense': '130',
                 'hp': '175',
                 'name': '大嘴雀',
                 'no': 22,
                 'skill_name': '',
                 'system': '飞'},
                {'attack': '60',
                 'defense': '40',
                 'hp': '60',
                 'name': '阿柏蛇',
                 'no': 23,
                 'skill_name': '缠绕 ',
                 'system': '毒/地'},
                {'attack': '150',
                 'defense': '120',
                 'hp': '180',
                 'name': '阿柏怪',
                 'no': 24,
                 'skill_name': '紧紧缠绕 ',
                 'system': '毒/地'},
                {'attack': '50',
                 'defense': '50',
                 'hp': '55',
                 'name': '皮卡丘',
                 'no': 25,
                 'skill_name': '十万伏特 ',
                 'system': '电'},
                {'attack': '150',
                 'defense': '150',
                 'hp': '190',
                 'name': '雷丘',
                 'no': 26,
                 'skill_name': '打雷攻击 ',
                 'system': '电'},
                {'attack': '50',
                 'defense': '55',
                 'hp': '60',
                 'name': '穿山鼠',
                 'no': 27,
                 'skill_name': '挖攻 ',
                 'system': '地'},
                {'attack': '150',
                 'defense': '155',
                 'hp': '180',
                 'name': '穿山王',
                 'no': 28,
                 'skill_name': '超级之星 ',
                 'system': '地'},
                {'attack': '40',
                 'defense': '40',
                 'hp': '35',
                 'name': '尼多蘭',
                 'no': 29,
                 'skill_name': '楸抓 ',
                 'system': '毒/地'},
                {'attack': '80',
                 'defense': '70',
                 'hp': '75',
                 'name': '尼多娜',
                 'no': 30,
                 'skill_name': '双飞踢 ',
                 'system': '毒/地'},
                {'attack': '160',
                 'defense': '150',
                 'hp': '180',
                 'name': '尼多后',
                 'no': 31,
                 'skill_name': '连飞踢 ',
                 'system': '毒/地'},
                {'attack': '35',
                 'defense': '35',
                 'hp': '35',
                 'name': '尼多朗',
                 'no': 32,
                 'skill_name': '楸抓 ',
                 'system': '毒/地'},
                {'attack': '75',
                 'defense': '65',
                 'hp': '65',
                 'name': '尼多力諾',
                 'no': 33,
                 'skill_name': '毒角刺 ',
                 'system': '毒/地'},
                {'attack': '170',
                 'defense': '160',
                 'hp': '200',
                 'name': '尼多王',
                 'no': 34,
                 'skill_name': '',
                 'system': '毒/地'},
                {'attack': '55',
                 'defense': '45',
                 'hp': '50',
                 'name': '皮皮',
                 'no': 35,
                 'skill_name': '重击 ',
                 'system': '普/超'},
                {'attack': '140',
                 'defense': '150',
                 'hp': '140',
                 'name': '皮可西',
                 'no': 36,
                 'skill_name': '连击 ',
                 'system': '普/超'},
                {'attack': '60',
                 'defense': '45',
                 'hp': '45',
                 'name': '六尾',
                 'no': 37,
                 'skill_name': '火焰喷射 ',
                 'system': '火'},
                {'attack': '170',
                 'defense': '140',
                 'hp': '150',
                 'name': '九尾',
                 'no': 38,
                 'skill_name': '大字爆 ',
                 'system': '火'},
                {'attack': '45',
                 'defense': '55',
                 'hp': '50',
                 'name': '胖丁',
                 'no': 39,
                 'skill_name': '',
                 'system': '普/超'},
                {'attack': '135',
                 'defense': '160',
                 'hp': '140',
                 'name': '胖可丁',
                 'no': 40,
                 'skill_name': '',
                 'system': '普/超'},
                {'attack': '40',
                 'defense': '45',
                 'hp': '50',
                 'name': '超音蝠',
                 'no': 41,
                 'skill_name': '',
                 'system': '飞/毒'},
                {'attack': '135',
                 'defense': '140',
                 'hp': '145',
                 'name': '大口蝠',
                 'no': 42,
                 'skill_name': '翅膀攻击 ',
                 'system': '飞/毒'},
                {'attack': '35',
                 'defense': '35',
                 'hp': '40',
                 'name': '走路草',
                 'no': 43,
                 'skill_name': '吸收 ',
                 'system': '草'},
                {'attack': '70',
                 'defense': '65',
                 'hp': '80',
                 'name': '臭臭花',
                 'no': 44,
                 'skill_name': '叶片剪 ',
                 'system': '草/毒'},
                {'attack': '140',
                 'defense': '130',
                 'hp': '150',
                 'name': '霸王花',
                 'no': 45,
                 'skill_name': '阳光烈焰 ',
                 'system': '草/毒'},
                {'attack': '40',
                 'defense': '40',
                 'hp': '60',
                 'name': '派拉斯',
                 'no': 46,
                 'skill_name': '楸抓 ',
                 'system': '虫/毒'},
                {'attack': '120',
                 'defense': '120',
                 'hp': '130',
                 'name': '派拉斯特',
                 'no': 47,
                 'skill_name': '',
                 'system': '虫/毒'},
                {'attack': '30',
                 'defense': '35',
                 'hp': '35',
                 'name': '毛球',
                 'no': 48,
                 'skill_name': '击杀 ',
                 'system': '虫'},
                {'attack': '100',
                 'defense': '120',
                 'hp': '135',
                 'name': '末入蛾',
                 'no': 49,
                 'skill_name': '',
                 'system': '虫'},
                {'attack': '40',
                 'defense': '45',
                 'hp': '55',
                 'name': '地鼠',
                 'no': 50,
                 'skill_name': '挖攻 ',
                 'system': '地'},
                {'attack': '120',
                 'defense': '130',
                 'hp': '165',
                 'name': '三头地鼠',
                 'no': 51,
                 'skill_name': '',
                 'system': '地'},
                {'attack': '50',
                 'defense': '40',
                 'hp': '45',
                 'name': '喵喵',
                 'no': 52,
                 'skill_name': '揪抓 ',
                 'system': '普'},
                {'attack': '135',
                 'defense': '130',
                 'hp': '150',
                 'name': '猫老大',
                 'no': 53,
                 'skill_name': '疯狂乱抓',
                 'system': '普'},
                {'attack': '20',
                 'defense': '25',
                 'hp': '55',
                 'name': '可达鸭',
                 'no': 54,
                 'skill_name': '击杀 ',
                 'system': '超/水'},
                {'attack': '150',
                 'defense': '160',
                 'hp': '175',
                 'name': '哥达鸭',
                 'no': 55,
                 'skill_name': '破坏死光 ',
                 'system': '超/水'},
                {'attack': '80',
                 'defense': '30',
                 'hp': '40',
                 'name': '猴怪',
                 'no': 56,
                 'skill_name': '拳击 ',
                 'system': '格'},
                {'attack': '230',
                 'defense': '100',
                 'hp': '140',
                 'name': '火暴猴',
                 'no': 57,
                 'skill_name': '地球摔 ',
                 'system': '格'},
                {'attack': '60',
                 'defense': '40',
                 'hp': '50',
                 'name': '卡蒂狗',
                 'no': 58,
                 'skill_name': '火焰喷射 ',
                 'system': '火'},
                {'attack': '175',
                 'defense': '130',
                 'hp': '160',
                 'name': '风速狗',
                 'no': 59,
                 'skill_name': '大字爆 ',
                 'system': '火'},
                {'attack': '35',
                 'defense': '40',
                 'hp': '35',
                 'name': '蚊香蝌蚪',
                 'no': 60,
                 'skill_name': '水枪 ',
                 'system': '水'},
                {'attack': '65',
                 'defense': '60',
                 'hp': '65',
                 'name': '蚊香蛙',
                 'no': 61,
                 'skill_name': '水泡兵 ',
                 'system': '水'},
                {'attack': '130',
                 'defense': '130',
                 'hp': '165',
                 'name': '快泳娃',
                 'no': 62,
                 'skill_name': '浪击 ',
                 'system': '水/格'},
                {'attack': '40',
                 'defense': '40',
                 'hp': '60',
                 'name': '凯西',
                 'no': 63,
                 'skill_name': '',
                 'system': '超'},
                {'attack': '100',
                 'defense': '100',
                 'hp': '85',
                 'name': '勇吉拉',
                 'no': 64,
                 'skill_name': '漂亮 ',
                 'system': '超'},
                {'attack': '170',
                 'defense': '170',
                 'hp': '185',
                 'name': '胡地',
                 'no': 65,
                 'skill_name': '破坏死光',
                 'system': '超'},
                {'attack': '70',
                 'defense': '50',
                 'hp': '45',
                 'name': '腕力',
                 'no': 66,
                 'skill_name': '拳击 ',
                 'system': '格'},
                {'attack': '100',
                 'defense': '85',
                 'hp': '105',
                 'name': '豪力',
                 'no': 67,
                 'skill_name': '',
                 'system': '格'},
                {'attack': '220',
                 'defense': '160',
                 'hp': '155',
                 'name': '怪力',
                 'no': 68,
                 'skill_name': '万吨拳击',
                 'system': '格'},
                {'attack': '45',
                 'defense': '40',
                 'hp': '50',
                 'name': '喇叭芽',
                 'no': 69,
                 'skill_name': '植物 ',
                 'system': '草/毒'},
                {'attack': '75',
                 'defense': '80',
                 'hp': '80',
                 'name': '口呆花',
                 'no': 70,
                 'skill_name': '叶片剪 ',
                 'system': '草/毒'},
                {'attack': '140',
                 'defense': '135',
                 'hp': '145',
                 'name': '大食花',
                 'no': 71,
                 'skill_name': '飞叶快刀',
                 'system': '草/毒'},
                {'attack': '40',
                 'defense': '35',
                 'hp': '50',
                 'name': '玛瑙水母',
                 'no': 72,
                 'skill_name': '水枪 ',
                 'system': '水/毒'},
                {'attack': '140',
                 'defense': '130',
                 'hp': '150',
                 'name': '毒刺水母',
                 'no': 73,
                 'skill_name': '',
                 'system': '水/毒'},
                {'attack': '60',
                 'defense': '65',
                 'hp': '70',
                 'name': '小拳石',
                 'no': 74,
                 'skill_name': '落石 ',
                 'system': '岩'},
                {'attack': '110',
                 'defense': '120',
                 'hp': '125',
                 'name': '隆隆石',
                 'no': 75,
                 'skill_name': '炸击 ',
                 'system': '岩'},
                {'attack': '180',
                 'defense': '185',
                 'hp': '190',
                 'name': '隆隆岩',
                 'no': 76,
                 'skill_name': '倒下 ',
                 'system': '岩'},
                {'attack': '65',
                 'defense': '35',
                 'hp': '45',
                 'name': '小火马',
                 'no': 77,
                 'skill_name': '火焰喷射',
                 'system': '火'},
                {'attack': '160',
                 'defense': '110',
                 'hp': '150',
                 'name': '烈焰马',
                 'no': 78,
                 'skill_name': '大字火 ',
                 'system': '火'},
                {'attack': '20',
                 'defense': '25',
                 'hp': '30',
                 'name': '呆呆兽',
                 'no': 79,
                 'skill_name': '击杀 ',
                 'system': '水'},
                {'attack': '120',
                 'defense': '95',
                 'hp': '100',
                 'name': '呆河马',
                 'no': 80,
                 'skill_name': '万吨拳击',
                 'system': '水/超'},
                {'attack': '50',
                 'defense': '55',
                 'hp': '60',
                 'name': '小磁怪',
                 'no': 81,
                 'skill_name': '雷电波 ',
                 'system': '电'},
                {'attack': '150',
                 'defense': '155',
                 'hp': '160',
                 'name': '三合一磁怪',
                 'no': 82,
                 'skill_name': '十万伏特',
                 'system': '电'},
                {'attack': '130',
                 'defense': '120',
                 'hp': '145',
                 'name': '大葱鸭',
                 'no': 83,
                 'skill_name': '大葱切 ',
                 'system': '飞'},
                {'attack': '50',
                 'defense': '45',
                 'hp': '55',
                 'name': '嘟嘟',
                 'no': 84,
                 'skill_name': '击杀 ',
                 'system': '飞'},
                {'attack': '135',
                 'defense': '130',
                 'hp': '170',
                 'name': '嘟嘟利',
                 'no': 85,
                 'skill_name': '教练啄食',
                 'system': '飞'},
                {'attack': '45',
                 'defense': '60',
                 'hp': '70',
                 'name': '小海狮',
                 'no': 86,
                 'skill_name': '冰冻拳 ',
                 'system': '水/冰'},
                {'attack': '145',
                 'defense': '145',
                 'hp': '170',
                 'name': '白海狮',
                 'no': 87,
                 'skill_name': '冰光线 ',
                 'system': '水/冰'},
                {'attack': '30',
                 'defense': '40',
                 'hp': '55',
                 'name': '臭泥',
                 'no': 88,
                 'skill_name': '击杀 ',
                 'system': '普/毒'},
                {'attack': '130',
                 'defense': '145',
                 'hp': '150',
                 'name': '臭臭泥',
                 'no': 89,
                 'skill_name': '',
                 'system': '普/毒'},
                {'attack': '30',
                 'defense': '90',
                 'hp': '100',
                 'name': '大舌贝',
                 'no': 90,
                 'skill_name': '',
                 'system': '水/冰'},
                {'attack': '120',
                 'defense': '280',
                 'hp': '280',
                 'name': '铁甲贝',
                 'no': 91,
                 'skill_name': '冰光线 ',
                 'system': '水/冰'},
                {'attack': '60',
                 'defense': '50',
                 'hp': '60',
                 'name': '鬼斯',
                 'no': 92,
                 'skill_name': '',
                 'system': '鬼'},
                {'attack': '125',
                 'defense': '100',
                 'hp': '110',
                 'name': '鬼斯通',
                 'no': 93,
                 'skill_name': '夜阴影 ',
                 'system': '鬼'},
                {'attack': '175',
                 'defense': '150',
                 'hp': '190',
                 'name': '耿鬼',
                 'no': 94,
                 'skill_name': '梦中食人兽',
                 'system': '鬼'},
                {'attack': '150',
                 'defense': '160',
                 'hp': '180',
                 'name': '大岩蛇',
                 'no': 95,
                 'skill_name': '束紧 ',
                 'system': '岩'},
                {'attack': '40',
                 'defense': '45',
                 'hp': '50',
                 'name': '索利普',
                 'no': 96,
                 'skill_name': '漂亮 ',
                 'system': '超'},
                {'attack': '135',
                 'defense': '145',
                 'hp': '110',
                 'name': '索利柏',
                 'no': 97,
                 'skill_name': '',
                 'system': '超'},
                {'attack': '30',
                 'defense': '65',
                 'hp': '70',
                 'name': '大闸蟹',
                 'no': 98,
                 'skill_name': '泡沫 ',
                 'system': '水'},
                {'attack': '150',
                 'defense': '170',
                 'hp': '185',
                 'name': '巨钳蟹',
                 'no': 99,
                 'skill_name': '浪击 ',
                 'system': '水'},
                {'attack': '50',
                 'defense': '55',
                 'hp': '60',
                 'name': '电气球',
                 'no': 100,
                 'skill_name': '自爆 ',
                 'system': '电'},
                {'attack': '155',
                 'defense': '155',
                 'hp': '170',
                 'name': '雷电球',
                 'no': 101,
                 'skill_name': '杀 ',
                 'system': '电'},
                {'attack': '45',
                 'defense': '60',
                 'hp': '60',
                 'name': '蛋蛋',
                 'no': 102,
                 'skill_name': '漂亮 ',
                 'system': '超/草'},
                {'attack': '130',
                 'defense': '140',
                 'hp': '145',
                 'name': '椰蛋树',
                 'no': 103,
                 'skill_name': '',
                 'system': '超/草'},
                {'attack': '40',
                 'defense': '45',
                 'hp': '55',
                 'name': '可拉可拉',
                 'no': 104,
                 'skill_name': '',
                 'system': '地'},
                {'attack': '110',
                 'defense': '130',
                 'hp': '150',
                 'name': '嘎拉嘎拉',
                 'no': 105,
                 'skill_name': '',
                 'system': '地'},
                {'attack': '185',
                 'defense': '140',
                 'hp': '160',
                 'name': '沙瓦郎',
                 'no': 106,
                 'skill_name': '连续踢 ',
                 'system': '格'},
                {'attack': '140',
                 'defense': '180',
                 'hp': '190',
                 'name': '艾比郎',
                 'no': 107,
                 'skill_name': '快拳 ',
                 'system': '格'},
                {'attack': '130',
                 'defense': '130',
                 'hp': '170',
                 'name': '大舌头',
                 'no': 108,
                 'skill_name': '舔舌头 ',
                 'system': '毒/普'},
                {'attack': '45',
                 'defense': '60',
                 'hp': '70',
                 'name': '瓦斯弹',
                 'no': 109,
                 'skill_name': '',
                 'system': '毒/岩'},
                {'attack': '135',
                 'defense': '170',
                 'hp': '185',
                 'name': '双弹瓦斯',
                 'no': 110,
                 'skill_name': '',
                 'system': '毒/岩'},
                {'attack': '60',
                 'defense': '65',
                 'hp': '75',
                 'name': '铁甲犀牛',
                 'no': 111,
                 'skill_name': '猛撞攻击',
                 'system': '地'},
                {'attack': '165',
                 'defense': '170',
                 'hp': '195',
                 'name': '铁甲暴龙',
                 'no': 112,
                 'skill_name': '万吨铁拳',
                 'system': '地/龙'},
                {'attack': '125',
                 'defense': '140',
                 'hp': '160',
                 'name': '吉利蛋',
                 'no': 113,
                 'skill_name': '漂亮 ',
                 'system': '超/普'},
                {'attack': '135',
                 'defense': '140',
                 'hp': '165',
                 'name': '蔓藤怪',
                 'no': 114,
                 'skill_name': '藤鞭 ',
                 'system': '草'},
                {'attack': '170',
                 'defense': '170',
                 'hp': '185',
                 'name': '袋龙',
                 'no': 115,
                 'skill_name': '地震 ',
                 'system': '地/龙'},
                {'attack': '60',
                 'defense': '50',
                 'hp': '70',
                 'name': '墨海马',
                 'no': 116,
                 'skill_name': '水枪 ',
                 'system': '水/毒'},
                {'attack': '155',
                 'defense': '130',
                 'hp': '150',
                 'name': '海刺龙',
                 'no': 117,
                 'skill_name': '浪击 ',
                 'system': '水/毒/龙'},
                {'attack': '45',
                 'defense': '45',
                 'hp': '60',
                 'name': '角金鱼',
                 'no': 118,
                 'skill_name': '击杀 ',
                 'system': '水/毒'},
                {'attack': '145',
                 'defense': '145',
                 'hp': '160',
                 'name': '金鱼王',
                 'no': 119,
                 'skill_name': '水泡兵 ',
                 'system': '水/毒'},
                {'attack': '55',
                 'defense': '65',
                 'hp': '55',
                 'name': '海星星',
                 'no': 120,
                 'skill_name': '水枪 ',
                 'system': '水/超'},
                {'attack': '135',
                 'defense': '155',
                 'hp': '155',
                 'name': '宝石海星',
                 'no': 121,
                 'skill_name': '巴巴拉 ',
                 'system': '水/超'},
                {'attack': '170',
                 'defense': '155',
                 'hp': '165',
                 'name': '吸盘魔偶',
                 'no': 122,
                 'skill_name': '重击 ',
                 'system': '普/超'},
                {'attack': '180',
                 'defense': '160',
                 'hp': '175',
                 'name': '飞天螳螂',
                 'no': 123,
                 'skill_name': '连续切 ',
                 'system': '虫/飞'},
                {'attack': '150',
                 'defense': '145',
                 'hp': '140',
                 'name': '迷唇姐',
                 'no': 124,
                 'skill_name': '冷冻拳 ',
                 'system': '冰/超'},
                {'attack': '145',
                 'defense': '145',
                 'hp': '145',
                 'name': '电击兽',
                 'no': 125,
                 'skill_name': '打雷攻击',
                 'system': '电'},
                {'attack': '190',
                 'defense': '95',
                 'hp': '135',
                 'name': '鸭嘴火龙',
                 'no': 126,
                 'skill_name': '大字火 ',
                 'system': '火'},
                {'attack': '125',
                 'defense': '195',
                 'hp': '200',
                 'name': '大甲',
                 'no': 127,
                 'skill_name': '角作角撞攻击',
                 'system': '虫'},
                {'attack': '135',
                 'defense': '120',
                 'hp': '125',
                 'name': '肯太罗',
                 'no': 128,
                 'skill_name': '猛撞攻击',
                 'system': '地'},
                {'attack': '20',
                 'defense': '20',
                 'hp': '20',
                 'name': '鲤鱼王',
                 'no': 129,
                 'skill_name': '',
                 'system': '水'},
                {'attack': '195',
                 'defense': '140',
                 'hp': '165',
                 'name': '暴鲤龙',
                 'no': 130,
                 'skill_name': '龙愤怒 ',
                 'system': '龙/水'},
                {'attack': '155',
                 'defense': '155',
                 'hp': '155',
                 'name': '乘龙',
                 'no': 131,
                 'skill_name': '巴巴拉 ',
                 'system': '水/龙'},
                {'attack': '10',
                 'defense': '10',
                 'hp': '10',
                 'name': '百变怪',
                 'no': 132,
                 'skill_name': '',
                 'system': '普'},
                {'attack': '45',
                 'defense': '45',
                 'hp': '55',
                 'name': '伊布',
                 'no': 133,
                 'skill_name': '揪抓 ',
                 'system': '普'},
                {'attack': '140',
                 'defense': '155',
                 'hp': '155',
                 'name': '水伊布',
                 'no': 134,
                 'skill_name': '浪击 ',
                 'system': '水'},
                {'attack': '140',
                 'defense': '140',
                 'hp': '155',
                 'name': '雷伊布',
                 'no': 135,
                 'skill_name': '打雷攻击',
                 'system': '电'},
                {'attack': '155',
                 'defense': '140',
                 'hp': '155',
                 'name': '火伊布',
                 'no': 136,
                 'skill_name': '大字火 ',
                 'system': '火'},
                {'attack': '180',
                 'defense': '160',
                 'hp': '165',
                 'name': '3D龙',
                 'no': 137,
                 'skill_name': '重击 ',
                 'system': '普/超'},
                {'attack': '55',
                 'defense': '70',
                 'hp': '70',
                 'name': '菊石兽',
                 'no': 138,
                 'skill_name': '',
                 'system': '岩/水'},
                {'attack': '140',
                 'defense': '170',
                 'hp': '160',
                 'name': '多刺菊石兽',
                 'no': 139,
                 'skill_name': '倒下 ',
                 'system': '岩/水'},
                {'attack': '70',
                 'defense': '55',
                 'hp': '65',
                 'name': '化石盔',
                 'no': 140,
                 'skill_name': '',
                 'system': '岩/水'},
                {'attack': '170',
                 'defense': '140',
                 'hp': '155',
                 'name': '镰刀盔',
                 'no': 141,
                 'skill_name': '倒下 ',
                 'system': '岩/水'},
                {'attack': '185',
                 'defense': '155',
                 'hp': '170',
                 'name': '化石翼龙',
                 'no': 142,
                 'skill_name': '钢铁之翼',
                 'system': '飞/龙'},
                {'attack': '180',
                 'defense': '180',
                 'hp': '300',
                 'name': '卡比兽',
                 'no': 143,
                 'skill_name': '',
                 'system': '普'},
                {'attack': '170',
                 'defense': '190',
                 'hp': '180',
                 'name': '急冻鸟',
                 'no': 144,
                 'skill_name': '暴风雪 ',
                 'system': '冰/飞'},
                {'attack': '170',
                 'defense': '170',
                 'hp': '180',
                 'name': '闪电鸟',
                 'no': 145,
                 'skill_name': '亿万伏特',
                 'system': '电'},
                {'attack': '190',
                 'defense': '170',
                 'hp': '180',
                 'name': '火焰鸟',
                 'no': 146,
                 'skill_name': '大字爆 ',
                 'system': '火'},
                {'attack': '40',
                 'defense': '45',
                 'hp': '45',
                 'name': '迷你龙',
                 'no': 147,
                 'skill_name': '击杀 ',
                 'system': '龙/水'},
                {'attack': '80',
                 'defense': '90',
                 'hp': '90',
                 'name': '哈克龙',
                 'no': 148,
                 'skill_name': '龙愤怒 ',
                 'system': '龙/水'},
                {'attack': '175',
                 'defense': '175',
                 'hp': '180',
                 'name': '快龙',
                 'no': 149,
                 'skill_name': '龙之怒 ',
                 'system': '龙/水/飞'},
                {'attack': '190',
                 'defense': '170',
                 'hp': '195',
                 'name': '超梦',
                 'no': 150,
                 'skill_name': '破坏死光',
                 'system': '超'},
                {'attack': '200',
                 'defense': '200',
                 'hp': '200',
                 'name': '梦幻',
                 'no': 151,
                 'skill_name': '??? ',
                 'system': '超'}]
