from django.contrib.auth.models import User

from game.models import Skill, Pokemon

skills = [
    {'system': '冰', 'power': 2, 'name': '冰冻拳'},
    {'system': '冰', 'power': 5, 'name': '冷冻拳'},
    {'system': '冰', 'power': 8, 'name': '冰光线'},
    {'system': '冰', 'power': 10, 'name': '暴风雪'},
    {'system': '地', 'power': 1, 'name': '缠绕'},
    {'system': '地', 'power': 2, 'name': '紧紧缠绕'},
    {'system': '地', 'power': 3, 'name': '揪抓'},
    {'system': '地', 'power': 4, 'name': '双飞踢'},
    {'system': '地', 'power': 5, 'name': '挖攻'},
    {'system': '地', 'power': 6, 'name': '连飞踢'},
    {'system': '地', 'power': 7, 'name': '猛撞攻击'},
    {'system': '地', 'power': 8, 'name': '超级之星'},
    {'system': '地', 'power': 9, 'name': '狂暴攻击'},
    {'system': '地', 'power': 10, 'name': '地震'},
    {'system': '岩', 'power': 3, 'name': '束紧'},
    {'system': '岩', 'power': 5, 'name': '落石'},
    {'system': '岩', 'power': 6, 'name': '倒下'},
    {'system': '岩', 'power': 15, 'name': '炸击'},
    {'system': '普', 'power': 2, 'name': '击杀'},
    {'system': '普', 'power': 3, 'name': '疯狂乱抓'},
    {'system': '普', 'power': 4, 'name': '连击'},
    {'system': '普', 'power': 5, 'name': '电光一闪'},
    {'system': '普', 'power': 6, 'name': '重击'},
    {'system': '普', 'power': 9, 'name': '万吨拳击'},
    {'system': '普', 'power': 10, 'name': '万吨铁拳'},
    {'system': '格', 'power': 3, 'name': '力量'},
    {'system': '格', 'power': 6, 'name': '连续踢'},
    {'system': '格', 'power': 7, 'name': '拳击'},
    {'system': '格', 'power': 8, 'name': '快拳'},
    {'system': '格', 'power': 10, 'name': '地球摔'},
    {'system': '毒', 'power': 2, 'name': '毒角刺'},
    {'system': '毒', 'power': 4, 'name': '楸抓'},
    {'system': '毒', 'power': 5, 'name': '舔舌头'},
    {'system': '毒', 'power': 8, 'name': '毒针'},
    {'system': '水', 'power': 4, 'name': '水枪'},
    {'system': '水', 'power': 5, 'name': '泡沫'},
    {'system': '水', 'power': 6, 'name': '水泡兵'},
    {'system': '水', 'power': 7, 'name': '浪击'},
    {'system': '水', 'power': 8, 'name': '巴巴拉'},
    {'system': '水', 'power': 10, 'name': '水炮'},
    {'system': '火', 'power': 5, 'name': '灰烬'},
    {'system': '火', 'power': 6, 'name': '喷射火焰'},
    {'system': '火', 'power': 7, 'name': '火焰喷射'},
    {'system': '火', 'power': 9, 'name': '大字火'},
    {'system': '火', 'power': 10, 'name': '大字爆'},
    {'system': '电', 'power': 5, 'name': '雷电波'},
    {'system': '电', 'power': 6, 'name': '十万伏特'},
    {'system': '电', 'power': 8, 'name': '打雷攻击'},
    {'system': '电', 'power': 10, 'name': '亿万伏特'},
    {'system': '电', 'power': 11, 'name': '自爆'},
    {'system': '电', 'power': 15, 'name': '杀'},
    {'system': '草', 'power': 2, 'name': '藤鞭'},
    {'system': '草', 'power': 4, 'name': '吸收'},
    {'system': '草', 'power': 5, 'name': '水蛭种子'},
    {'system': '草', 'power': 6, 'name': '植物'},
    {'system': '草', 'power': 7, 'name': '叶片剪'},
    {'system': '草', 'power': 8, 'name': '飞叶快刀'},
    {'system': '草', 'power': 9, 'name': '阳光烈焰'},
    {'system': '虫', 'power': 3, 'name': '连续切'},
    {'system': '虫', 'power': 6, 'name': '角作角撞攻击'},
    {'system': '虫', 'power': 8, 'name': '催眠粉'},
    {'system': '超', 'power': 7, 'name': '漂亮'},
    {'system': '超', 'power': 10, 'name': '破坏死光'},
    {'system': '超', 'power': 12, 'name': '???'},
    {'system': '飞', 'power': 4, 'name': '啄击'},
    {'system': '飞', 'power': 5, 'name': '教练啄食'},
    {'system': '飞', 'power': 7, 'name': '翅膀攻击'},
    {'system': '飞', 'power': 8, 'name': '大葱切'},
    {'system': '飞', 'power': 9, 'name': '飞击'},
    {'system': '飞', 'power': 10, 'name': '钢铁之翼'},
    {'system': '鬼', 'power': 7, 'name': '夜阴影'},
    {'system': '鬼', 'power': 10, 'name': '梦中食人兽'},
    {'system': '龙', 'power': 7, 'name': '龙愤怒'},
    {'system': '龙', 'power': 10, 'name': '龙之怒'},
]

pokemons = [
    {
        'no': 1,
        'name': '妙蛙种子',
        'system': '草',
        'attack': 4,
        'defense': 5,
        'hp': 5,
        'skill_name': '藤鞭',
        'evo_no': 2,
    },
    {
        'no': 2,
        'name': '妙蛙草',
        'system': '草',
        'attack': 8,
        'defense': 9,
        'hp': 10,
        'skill_name': '水蛭种子',
        'evo_no': 3,
    },
    {
        'no': 3,
        'name': '妙蛙花',
        'system': '草',
        'attack': 15,
        'defense': 15,
        'hp': 18,
        'skill_name': '飞叶快刀',
        'evo_no': 0,
    },
    {
        'no': 4,
        'name': '小火龙',
        'system': '火',
        'attack': 7,
        'defense': 3,
        'hp': 4,
        'skill_name': '灰烬',
        'evo_no': 5,
    },
    {
        'no': 5,
        'name': '火恐龙',
        'system': '火',
        'attack': 13,
        'defense': 6,
        'hp': 9,
        'skill_name': '火焰喷射',
        'evo_no': 6,
    },
    {
        'no': 6,
        'name': '喷火龙',
        'system': '火',
        'attack': 21,
        'defense': 11,
        'hp': 17,
        'skill_name': '大字火',
        'evo_no': 0,
    },
    {
        'no': 7,
        'name': '杰尼龟',
        'system': '水',
        'attack': 4,
        'defense': 7,
        'hp': 6,
        'skill_name': '水枪',
        'evo_no': 8,
    },
    {
        'no': 8,
        'name': '卡咪龟',
        'system': '水',
        'attack': 6,
        'defense': 15,
        'hp': 12,
        'skill_name': '泡沫',
        'evo_no': 9,
    },
    {
        'no': 9,
        'name': '水箭龟',
        'system': '水',
        'attack': 12,
        'defense': 25,
        'hp': 22,
        'skill_name': '水炮',
        'evo_no': 0,
    },
    {
        'no': 10,
        'name': '绿毛虫',
        'system': '虫',
        'attack': 3,
        'defense': 4,
        'hp': 5,
        'skill_name': '连续切',
        'evo_no': 11,
    },
    {
        'no': 11,
        'name': '铁甲蛹',
        'system': '虫',
        'attack': 2,
        'defense': 13,
        'hp': 20,
        'skill_name': '角作角撞攻击',
        'evo_no': 12,
    },
    {
        'no': 12,
        'name': '八大蝴',
        'system': '虫/毒',
        'attack': 13,
        'defense': 10,
        'hp': 17,
        'skill_name': '催眠粉',
        'evo_no': 0,
    },
    {
        'no': 13,
        'name': '独角虫',
        'system': '虫/毒',
        'attack': 4,
        'defense': 3,
        'hp': 4,
        'skill_name': '毒角刺',
        'evo_no': 14,
    },
    {
        'no': 14,
        'name': '铁壳昆',
        'system': '虫/毒',
        'attack': 2,
        'defense': 13,
        'hp': 19,
        'skill_name': '角作角撞攻击',
        'evo_no': 15,
    },
    {
        'no': 15,
        'name': '大针蜂',
        'system': '虫/毒',
        'attack': 14,
        'defense': 9,
        'hp': 17,
        'skill_name': '毒针',
        'evo_no': 0,
    },
    {
        'no': 16,
        'name': '波波',
        'system': '飞',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '啄击',
        'evo_no': 17,
    },
    {
        'no': 17,
        'name': '比比鸟',
        'system': '飞',
        'attack': 8,
        'defense': 8,
        'hp': 9,
        'skill_name': '啄击',
        'evo_no': 18,
    },
    {
        'no': 18,
        'name': '比雕',
        'system': '飞',
        'attack': 15,
        'defense': 14,
        'hp': 18,
        'skill_name': '飞击',
        'evo_no': 0,
    },
    {
        'no': 19,
        'name': '小拉达',
        'system': '地',
        'attack': 5,
        'defense': 4,
        'hp': 4,
        'skill_name': '揪抓',
        'evo_no': 20,
    },
    {
        'no': 20,
        'name': '拉达',
        'system': '地',
        'attack': 13,
        'defense': 13,
        'hp': 17,
        'skill_name': '猛撞攻击',
        'evo_no': 0,
    },
    {
        'no': 21,
        'name': '烈雀',
        'system': '飞',
        'attack': 5,
        'defense': 4,
        'hp': 4,
        'skill_name': '啄击',
        'evo_no': 22,
    },
    {
        'no': 22,
        'name': '大嘴雀',
        'system': '飞',
        'attack': 15,
        'defense': 13,
        'hp': 17,
        'skill_name': '翅膀攻击',
        'evo_no': 0,
    },
    {
        'no': 23,
        'name': '阿柏蛇',
        'system': '毒/地',
        'attack': 6,
        'defense': 4,
        'hp': 6,
        'skill_name': '缠绕',
        'evo_no': 24,
    },
    {
        'no': 24,
        'name': '阿柏怪',
        'system': '毒/地',
        'attack': 15,
        'defense': 12,
        'hp': 18,
        'skill_name': '紧紧缠绕',
        'evo_no': 0,
    },
    {
        'no': 25,
        'name': '皮卡丘',
        'system': '电',
        'attack': 5,
        'defense': 5,
        'hp': 5,
        'skill_name': '十万伏特',
        'evo_no': 26,
    },
    {
        'no': 26,
        'name': '雷丘',
        'system': '电',
        'attack': 15,
        'defense': 15,
        'hp': 19,
        'skill_name': '打雷攻击',
        'evo_no': 0,
    },
    {
        'no': 27,
        'name': '穿山鼠',
        'system': '地',
        'attack': 5,
        'defense': 5,
        'hp': 6,
        'skill_name': '挖攻',
        'evo_no': 28,
    },
    {
        'no': 28,
        'name': '穿山王',
        'system': '地',
        'attack': 15,
        'defense': 15,
        'hp': 18,
        'skill_name': '超级之星',
        'evo_no': 0,
    },
    {
        'no': 29,
        'name': '尼多蘭',
        'system': '毒/地',
        'attack': 4,
        'defense': 4,
        'hp': 3,
        'skill_name': '楸抓',
        'evo_no': 30,
    },
    {
        'no': 30,
        'name': '尼多娜',
        'system': '毒/地',
        'attack': 8,
        'defense': 7,
        'hp': 7,
        'skill_name': '双飞踢',
        'evo_no': 31,
    },
    {
        'no': 31,
        'name': '尼多后',
        'system': '毒/地',
        'attack': 16,
        'defense': 15,
        'hp': 18,
        'skill_name': '连飞踢',
        'evo_no': 0,
    },
    {
        'no': 32,
        'name': '尼多朗',
        'system': '毒/地',
        'attack': 3,
        'defense': 3,
        'hp': 3,
        'skill_name': '楸抓',
        'evo_no': 33,
    },
    {
        'no': 33,
        'name': '尼多力諾',
        'system': '毒/地',
        'attack': 7,
        'defense': 6,
        'hp': 6,
        'skill_name': '双飞踢',
        'evo_no': 34,
    },
    {
        'no': 34,
        'name': '尼多王',
        'system': '毒/地',
        'attack': 17,
        'defense': 16,
        'hp': 20,
        'skill_name': '狂暴攻击',
        'evo_no': 0,
    },
    {
        'no': 35,
        'name': '皮皮',
        'system': '普/超',
        'attack': 5,
        'defense': 4,
        'hp': 5,
        'skill_name': '重击',
        'evo_no': 36,
    },
    {
        'no': 36,
        'name': '皮可西',
        'system': '普/超',
        'attack': 14,
        'defense': 15,
        'hp': 14,
        'skill_name': '连击',
        'evo_no': 0,
    },
    {
        'no': 37,
        'name': '六尾',
        'system': '火',
        'attack': 6,
        'defense': 4,
        'hp': 4,
        'skill_name': '火焰喷射',
        'evo_no': 38,
    },
    {
        'no': 38,
        'name': '九尾',
        'system': '火',
        'attack': 17,
        'defense': 14,
        'hp': 15,
        'skill_name': '大字爆',
        'evo_no': 0,
    },
    {
        'no': 39,
        'name': '胖丁',
        'system': '普/超',
        'attack': 4,
        'defense': 5,
        'hp': 5,
        'skill_name': '',
        'evo_no': 40,
    },
    {
        'no': 40,
        'name': '胖可丁',
        'system': '普/超',
        'attack': 13,
        'defense': 16,
        'hp': 14,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 41,
        'name': '超音蝠',
        'system': '飞/毒',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '',
        'evo_no': 42,
    },
    {
        'no': 42,
        'name': '大口蝠',
        'system': '飞/毒',
        'attack': 13,
        'defense': 14,
        'hp': 14,
        'skill_name': '翅膀攻击',
        'evo_no': 0,
    },
    {
        'no': 43,
        'name': '走路草',
        'system': '草',
        'attack': 3,
        'defense': 3,
        'hp': 4,
        'skill_name': '吸收',
        'evo_no': 44,
    },
    {
        'no': 44,
        'name': '臭臭花',
        'system': '草/毒',
        'attack': 7,
        'defense': 6,
        'hp': 8,
        'skill_name': '叶片剪',
        'evo_no': 45,
    },
    {
        'no': 45,
        'name': '霸王花',
        'system': '草/毒',
        'attack': 14,
        'defense': 13,
        'hp': 15,
        'skill_name': '阳光烈焰',
        'evo_no': 0,
    },
    {
        'no': 46,
        'name': '派拉斯',
        'system': '虫/毒',
        'attack': 4,
        'defense': 4,
        'hp': 6,
        'skill_name': '楸抓',
        'evo_no': 47,
    },
    {
        'no': 47,
        'name': '派拉斯特',
        'system': '虫/毒',
        'attack': 12,
        'defense': 12,
        'hp': 13,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 48,
        'name': '毛球',
        'system': '虫',
        'attack': 3,
        'defense': 3,
        'hp': 3,
        'skill_name': '击杀',
        'evo_no': 49,
    },
    {
        'no': 49,
        'name': '末入蛾',
        'system': '虫',
        'attack': 10,
        'defense': 12,
        'hp': 13,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 50,
        'name': '地鼠',
        'system': '地',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '挖攻',
        'evo_no': 51,
    },
    {
        'no': 51,
        'name': '三头地鼠',
        'system': '地',
        'attack': 12,
        'defense': 13,
        'hp': 16,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 52,
        'name': '喵喵',
        'system': '普',
        'attack': 5,
        'defense': 4,
        'hp': 4,
        'skill_name': '揪抓',
        'evo_no': 53,
    },
    {
        'no': 53,
        'name': '猫老大',
        'system': '普',
        'attack': 13,
        'defense': 13,
        'hp': 15,
        'skill_name': '疯狂乱抓',
        'evo_no': 0,
    },
    {
        'no': 54,
        'name': '可达鸭',
        'system': '超/水',
        'attack': 2,
        'defense': 2,
        'hp': 5,
        'skill_name': '击杀',
        'evo_no': 55,
    },
    {
        'no': 55,
        'name': '哥达鸭',
        'system': '超/水',
        'attack': 15,
        'defense': 16,
        'hp': 17,
        'skill_name': '破坏死光',
        'evo_no': 0,
    },
    {
        'no': 56,
        'name': '猴怪',
        'system': '格',
        'attack': 8,
        'defense': 3,
        'hp': 4,
        'skill_name': '拳击',
        'evo_no': 57,
    },
    {
        'no': 57,
        'name': '火暴猴',
        'system': '格',
        'attack': 23,
        'defense': 10,
        'hp': 14,
        'skill_name': '地球摔',
        'evo_no': 0,
    },
    {
        'no': 58,
        'name': '卡蒂狗',
        'system': '火',
        'attack': 6,
        'defense': 4,
        'hp': 5,
        'skill_name': '火焰喷射',
        'evo_no': 59,
    },
    {
        'no': 59,
        'name': '风速狗',
        'system': '火',
        'attack': 17,
        'defense': 13,
        'hp': 16,
        'skill_name': '大字爆',
        'evo_no': 0,
    },
    {
        'no': 60,
        'name': '蚊香蝌蚪',
        'system': '水',
        'attack': 3,
        'defense': 4,
        'hp': 3,
        'skill_name': '水枪',
        'evo_no': 61,
    },
    {
        'no': 61,
        'name': '蚊香蛙',
        'system': '水',
        'attack': 6,
        'defense': 6,
        'hp': 6,
        'skill_name': '水泡兵',
        'evo_no': 62,
    },
    {
        'no': 62,
        'name': '快泳娃',
        'system': '水/格',
        'attack': 13,
        'defense': 13,
        'hp': 16,
        'skill_name': '浪击',
        'evo_no': 0,
    },
    {
        'no': 63,
        'name': '凯西',
        'system': '超',
        'attack': 4,
        'defense': 4,
        'hp': 6,
        'skill_name': '',
        'evo_no': 64,
    },
    {
        'no': 64,
        'name': '勇吉拉',
        'system': '超',
        'attack': 10,
        'defense': 10,
        'hp': 8,
        'skill_name': '漂亮',
        'evo_no': 65,
    },
    {
        'no': 65,
        'name': '胡地',
        'system': '超',
        'attack': 17,
        'defense': 17,
        'hp': 18,
        'skill_name': '破坏死光',
        'evo_no': 0,
    },
    {
        'no': 66,
        'name': '腕力',
        'system': '格',
        'attack': 7,
        'defense': 5,
        'hp': 4,
        'skill_name': '拳击',
        'evo_no': 67,
    },
    {
        'no': 67,
        'name': '豪力',
        'system': '格',
        'attack': 10,
        'defense': 8,
        'hp': 10,
        'skill_name': '',
        'evo_no': 68,
    },
    {
        'no': 68,
        'name': '怪力',
        'system': '格',
        'attack': 22,
        'defense': 16,
        'hp': 15,
        'skill_name': '万吨拳击',
        'evo_no': 0,
    },
    {
        'no': 69,
        'name': '喇叭芽',
        'system': '草/毒',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '植物',
        'evo_no': 70,
    },
    {
        'no': 70,
        'name': '口呆花',
        'system': '草/毒',
        'attack': 7,
        'defense': 8,
        'hp': 8,
        'skill_name': '叶片剪',
        'evo_no': 71,
    },
    {
        'no': 71,
        'name': '大食花',
        'system': '草/毒',
        'attack': 14,
        'defense': 13,
        'hp': 14,
        'skill_name': '飞叶快刀',
        'evo_no': 0,
    },
    {
        'no': 72,
        'name': '玛瑙水母',
        'system': '水/毒',
        'attack': 4,
        'defense': 3,
        'hp': 5,
        'skill_name': '水枪',
        'evo_no': 73,
    },
    {
        'no': 73,
        'name': '毒刺水母',
        'system': '水/毒',
        'attack': 14,
        'defense': 13,
        'hp': 15,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 74,
        'name': '小拳石',
        'system': '岩',
        'attack': 6,
        'defense': 6,
        'hp': 7,
        'skill_name': '落石',
        'evo_no': 75,
    },
    {
        'no': 75,
        'name': '隆隆石',
        'system': '岩',
        'attack': 11,
        'defense': 12,
        'hp': 12,
        'skill_name': '炸击',
        'evo_no': 76,
    },
    {
        'no': 76,
        'name': '隆隆岩',
        'system': '岩',
        'attack': 18,
        'defense': 18,
        'hp': 19,
        'skill_name': '倒下',
        'evo_no': 0,
    },
    {
        'no': 77,
        'name': '小火马',
        'system': '火',
        'attack': 6,
        'defense': 3,
        'hp': 4,
        'skill_name': '火焰喷射',
        'evo_no': 78,
    },
    {
        'no': 78,
        'name': '烈焰马',
        'system': '火',
        'attack': 16,
        'defense': 11,
        'hp': 15,
        'skill_name': '大字火',
        'evo_no': 0,
    },
    {
        'no': 79,
        'name': '呆呆兽',
        'system': '水',
        'attack': 2,
        'defense': 2,
        'hp': 3,
        'skill_name': '击杀',
        'evo_no': 80,
    },
    {
        'no': 80,
        'name': '呆河马',
        'system': '水/超',
        'attack': 12,
        'defense': 9,
        'hp': 10,
        'skill_name': '万吨拳击',
        'evo_no': 0,
    },
    {
        'no': 81,
        'name': '小磁怪',
        'system': '电',
        'attack': 5,
        'defense': 5,
        'hp': 6,
        'skill_name': '雷电波',
        'evo_no': 82,
    },
    {
        'no': 82,
        'name': '三合一磁怪',
        'system': '电',
        'attack': 15,
        'defense': 15,
        'hp': 16,
        'skill_name': '十万伏特',
        'evo_no': 0,
    },
    {
        'no': 83,
        'name': '大葱鸭',
        'system': '飞',
        'attack': 13,
        'defense': 12,
        'hp': 14,
        'skill_name': '大葱切',
        'evo_no': 0,
    },
    {
        'no': 84,
        'name': '嘟嘟',
        'system': '飞',
        'attack': 5,
        'defense': 4,
        'hp': 5,
        'skill_name': '击杀',
        'evo_no': 85,
    },
    {
        'no': 85,
        'name': '嘟嘟利',
        'system': '飞',
        'attack': 13,
        'defense': 13,
        'hp': 17,
        'skill_name': '教练啄食',
        'evo_no': 0,
    },
    {
        'no': 86,
        'name': '小海狮',
        'system': '水/冰',
        'attack': 4,
        'defense': 6,
        'hp': 7,
        'skill_name': '冰冻拳',
        'evo_no': 87,
    },
    {
        'no': 87,
        'name': '白海狮',
        'system': '水/冰',
        'attack': 14,
        'defense': 14,
        'hp': 17,
        'skill_name': '冰光线',
        'evo_no': 0,
    },
    {
        'no': 88,
        'name': '臭泥',
        'system': '普/毒',
        'attack': 3,
        'defense': 4,
        'hp': 5,
        'skill_name': '击杀',
        'evo_no': 89,
    },
    {
        'no': 89,
        'name': '臭臭泥',
        'system': '普/毒',
        'attack': 13,
        'defense': 14,
        'hp': 15,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 90,
        'name': '大舌贝',
        'system': '水/冰',
        'attack': 3,
        'defense': 9,
        'hp': 10,
        'skill_name': '',
        'evo_no': 91,
    },
    {
        'no': 91,
        'name': '铁甲贝',
        'system': '水/冰',
        'attack': 12,
        'defense': 28,
        'hp': 28,
        'skill_name': '冰光线',
        'evo_no': 0,
    },
    {
        'no': 92,
        'name': '鬼斯',
        'system': '鬼',
        'attack': 6,
        'defense': 5,
        'hp': 6,
        'skill_name': '',
        'evo_no': 93,
    },
    {
        'no': 93,
        'name': '鬼斯通',
        'system': '鬼',
        'attack': 12,
        'defense': 10,
        'hp': 11,
        'skill_name': '夜阴影',
        'evo_no': 94,
    },
    {
        'no': 94,
        'name': '耿鬼',
        'system': '鬼',
        'attack': 17,
        'defense': 15,
        'hp': 19,
        'skill_name': '梦中食人兽',
        'evo_no': 0,
    },
    {
        'no': 95,
        'name': '大岩蛇',
        'system': '岩',
        'attack': 15,
        'defense': 16,
        'hp': 18,
        'skill_name': '束紧',
        'evo_no': 0,
    },
    {
        'no': 96,
        'name': '索利普',
        'system': '超',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '漂亮',
        'evo_no': 97,
    },
    {
        'no': 97,
        'name': '索利柏',
        'system': '超',
        'attack': 13,
        'defense': 14,
        'hp': 11,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 98,
        'name': '大闸蟹',
        'system': '水',
        'attack': 3,
        'defense': 6,
        'hp': 7,
        'skill_name': '泡沫',
        'evo_no': 99,
    },
    {
        'no': 99,
        'name': '巨钳蟹',
        'system': '水',
        'attack': 15,
        'defense': 17,
        'hp': 18,
        'skill_name': '浪击',
        'evo_no': 0,
    },
    {
        'no': 100,
        'name': '电气球',
        'system': '电',
        'attack': 5,
        'defense': 5,
        'hp': 6,
        'skill_name': '自爆',
        'evo_no': 101,
    },
    {
        'no': 101,
        'name': '雷电球',
        'system': '电',
        'attack': 15,
        'defense': 15,
        'hp': 17,
        'skill_name': '杀',
        'evo_no': 0,
    },
    {
        'no': 102,
        'name': '蛋蛋',
        'system': '超/草',
        'attack': 4,
        'defense': 6,
        'hp': 6,
        'skill_name': '漂亮',
        'evo_no': 103,
    },
    {
        'no': 103,
        'name': '椰蛋树',
        'system': '超/草',
        'attack': 13,
        'defense': 14,
        'hp': 14,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 104,
        'name': '可拉可拉',
        'system': '地',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '',
        'evo_no': 105,
    },
    {
        'no': 105,
        'name': '嘎拉嘎拉',
        'system': '地',
        'attack': 11,
        'defense': 13,
        'hp': 15,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 106,
        'name': '沙瓦郎',
        'system': '格',
        'attack': 18,
        'defense': 14,
        'hp': 16,
        'skill_name': '连续踢',
        'evo_no': 0,
    },
    {
        'no': 107,
        'name': '艾比郎',
        'system': '格',
        'attack': 14,
        'defense': 18,
        'hp': 19,
        'skill_name': '快拳',
        'evo_no': 0,
    },
    {
        'no': 108,
        'name': '大舌头',
        'system': '毒/普',
        'attack': 13,
        'defense': 13,
        'hp': 17,
        'skill_name': '舔舌头',
        'evo_no': 0,
    },
    {
        'no': 109,
        'name': '瓦斯弹',
        'system': '毒/岩',
        'attack': 4,
        'defense': 6,
        'hp': 7,
        'skill_name': '',
        'evo_no': 110,
    },
    {
        'no': 110,
        'name': '双弹瓦斯',
        'system': '毒/岩',
        'attack': 13,
        'defense': 17,
        'hp': 18,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 111,
        'name': '铁甲犀牛',
        'system': '地',
        'attack': 6,
        'defense': 6,
        'hp': 7,
        'skill_name': '猛撞攻击',
        'evo_no': 112,
    },
    {
        'no': 112,
        'name': '铁甲暴龙',
        'system': '地/龙',
        'attack': 16,
        'defense': 17,
        'hp': 19,
        'skill_name': '万吨铁拳',
        'evo_no': 0,
    },
    {
        'no': 113,
        'name': '吉利蛋',
        'system': '超/普',
        'attack': 12,
        'defense': 14,
        'hp': 16,
        'skill_name': '漂亮',
        'evo_no': 0,
    },
    {
        'no': 114,
        'name': '蔓藤怪',
        'system': '草',
        'attack': 13,
        'defense': 14,
        'hp': 16,
        'skill_name': '藤鞭',
        'evo_no': 0,
    },
    {
        'no': 115,
        'name': '袋龙',
        'system': '地/龙',
        'attack': 17,
        'defense': 17,
        'hp': 18,
        'skill_name': '地震',
        'evo_no': 0,
    },
    {
        'no': 116,
        'name': '墨海马',
        'system': '水/毒',
        'attack': 6,
        'defense': 5,
        'hp': 7,
        'skill_name': '水枪',
        'evo_no': 117,
    },
    {
        'no': 117,
        'name': '海刺龙',
        'system': '水/毒/龙',
        'attack': 15,
        'defense': 13,
        'hp': 15,
        'skill_name': '浪击',
        'evo_no': 0,
    },
    {
        'no': 118,
        'name': '角金鱼',
        'system': '水/毒',
        'attack': 4,
        'defense': 4,
        'hp': 6,
        'skill_name': '击杀',
        'evo_no': 119,
    },
    {
        'no': 119,
        'name': '金鱼王',
        'system': '水/毒',
        'attack': 14,
        'defense': 14,
        'hp': 16,
        'skill_name': '水泡兵',
        'evo_no': 0,
    },
    {
        'no': 120,
        'name': '海星星',
        'system': '水/超',
        'attack': 5,
        'defense': 6,
        'hp': 5,
        'skill_name': '水枪',
        'evo_no': 121,
    },
    {
        'no': 121,
        'name': '宝石海星',
        'system': '水/超',
        'attack': 13,
        'defense': 15,
        'hp': 15,
        'skill_name': '巴巴拉',
        'evo_no': 0,
    },
    {
        'no': 122,
        'name': '吸盘魔偶',
        'system': '普/超',
        'attack': 17,
        'defense': 15,
        'hp': 16,
        'skill_name': '重击',
        'evo_no': 0,
    },
    {
        'no': 123,
        'name': '飞天螳螂',
        'system': '虫/飞',
        'attack': 18,
        'defense': 16,
        'hp': 17,
        'skill_name': '连续切',
        'evo_no': 0,
    },
    {
        'no': 124,
        'name': '迷唇姐',
        'system': '冰/超',
        'attack': 15,
        'defense': 14,
        'hp': 14,
        'skill_name': '冷冻拳',
        'evo_no': 0,
    },
    {
        'no': 125,
        'name': '电击兽',
        'system': '电',
        'attack': 14,
        'defense': 14,
        'hp': 14,
        'skill_name': '打雷攻击',
        'evo_no': 0,
    },
    {
        'no': 126,
        'name': '鸭嘴火龙',
        'system': '火',
        'attack': 19,
        'defense': 9,
        'hp': 13,
        'skill_name': '大字火',
        'evo_no': 0,
    },
    {
        'no': 127,
        'name': '大甲',
        'system': '虫',
        'attack': 12,
        'defense': 19,
        'hp': 20,
        'skill_name': '角作角撞攻击',
        'evo_no': 0,
    },
    {
        'no': 128,
        'name': '肯太罗',
        'system': '地',
        'attack': 13,
        'defense': 12,
        'hp': 12,
        'skill_name': '猛撞攻击',
        'evo_no': 0,
    },
    {
        'no': 129,
        'name': '鲤鱼王',
        'system': '水',
        'attack': 2,
        'defense': 2,
        'hp': 2,
        'skill_name': '',
        'evo_no': 130,
    },
    {
        'no': 130,
        'name': '暴鲤龙',
        'system': '龙/水',
        'attack': 19,
        'defense': 14,
        'hp': 16,
        'skill_name': '龙愤怒',
        'evo_no': 0,
    },
    {
        'no': 131,
        'name': '乘龙',
        'system': '水/龙',
        'attack': 15,
        'defense': 15,
        'hp': 15,
        'skill_name': '巴巴拉',
        'evo_no': 0,
    },
    {
        'no': 132,
        'name': '百变怪',
        'system': '普',
        'attack': 1,
        'defense': 1,
        'hp': 1,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 133,
        'name': '伊布',
        'system': '普',
        'attack': 4,
        'defense': 4,
        'hp': 5,
        'skill_name': '揪抓',
        'evo_no': 0,
    },
    {
        'no': 134,
        'name': '水伊布',
        'system': '水',
        'attack': 14,
        'defense': 15,
        'hp': 15,
        'skill_name': '浪击',
        'evo_no': 0,
    },
    {
        'no': 135,
        'name': '雷伊布',
        'system': '电',
        'attack': 14,
        'defense': 14,
        'hp': 15,
        'skill_name': '打雷攻击',
        'evo_no': 0,
    },
    {
        'no': 136,
        'name': '火伊布',
        'system': '火',
        'attack': 15,
        'defense': 14,
        'hp': 15,
        'skill_name': '大字火',
        'evo_no': 0,
    },
    {
        'no': 137,
        'name': '3D龙',
        'system': '普/超',
        'attack': 18,
        'defense': 16,
        'hp': 16,
        'skill_name': '重击',
        'evo_no': 0,
    },
    {
        'no': 138,
        'name': '菊石兽',
        'system': '岩/水',
        'attack': 5,
        'defense': 7,
        'hp': 7,
        'skill_name': '',
        'evo_no': 139,
    },
    {
        'no': 139,
        'name': '多刺菊石兽',
        'system': '岩/水',
        'attack': 14,
        'defense': 17,
        'hp': 16,
        'skill_name': '倒下',
        'evo_no': 0,
    },
    {
        'no': 140,
        'name': '化石盔',
        'system': '岩/水',
        'attack': 7,
        'defense': 5,
        'hp': 6,
        'skill_name': '',
        'evo_no': 141,
    },
    {
        'no': 141,
        'name': '镰刀盔',
        'system': '岩/水',
        'attack': 17,
        'defense': 14,
        'hp': 15,
        'skill_name': '倒下',
        'evo_no': 0,
    },
    {
        'no': 142,
        'name': '化石翼龙',
        'system': '飞/龙',
        'attack': 18,
        'defense': 15,
        'hp': 17,
        'skill_name': '钢铁之翼',
        'evo_no': 0,
    },
    {
        'no': 143,
        'name': '卡比兽',
        'system': '普',
        'attack': 18,
        'defense': 18,
        'hp': 30,
        'skill_name': '',
        'evo_no': 0,
    },
    {
        'no': 144,
        'name': '急冻鸟',
        'system': '冰/飞',
        'attack': 17,
        'defense': 19,
        'hp': 18,
        'skill_name': '暴风雪',
        'evo_no': 0,
    },
    {
        'no': 145,
        'name': '闪电鸟',
        'system': '电',
        'attack': 17,
        'defense': 17,
        'hp': 18,
        'skill_name': '亿万伏特',
        'evo_no': 0,
    },
    {
        'no': 146,
        'name': '火焰鸟',
        'system': '火',
        'attack': 19,
        'defense': 17,
        'hp': 18,
        'skill_name': '大字爆',
        'evo_no': 0,
    },
    {
        'no': 147,
        'name': '迷你龙',
        'system': '龙/水',
        'attack': 4,
        'defense': 4,
        'hp': 4,
        'skill_name': '击杀',
        'evo_no': 148,
    },
    {
        'no': 148,
        'name': '哈克龙',
        'system': '龙/水',
        'attack': 8,
        'defense': 9,
        'hp': 9,
        'skill_name': '龙愤怒',
        'evo_no': 149,
    },
    {
        'no': 149,
        'name': '快龙',
        'system': '龙/水/飞',
        'attack': 17,
        'defense': 17,
        'hp': 18,
        'skill_name': '龙之怒',
        'evo_no': 0,
    },
    {
        'no': 150,
        'name': '超梦',
        'system': '超',
        'attack': 19,
        'defense': 17,
        'hp': 19,
        'skill_name': '破坏死光',
        'evo_no': 0,
    },
    {
        'no': 151,
        'name': '梦幻',
        'system': '超',
        'attack': 20,
        'defense': 20,
        'hp': 20,
        'skill_name': '???',
        'evo_no': 0,
    },
]


def init():

    if not User.objects.exists():
        u = User.objects.create(username='admin', is_staff=True, is_superuser=True)
        u.set_password('admin')
        u.save()

        u = User.objects.create(username='aa1', is_staff=True)
        u.set_password('aa1')
        u.save()

        u = User.objects.create(username='aa2', is_staff=True)
        u.set_password('aa2')
        u.save()

    
    if not Skill.objects.exists():
        print('init skills')
        for s in skills:
            Skill.objects.create(name=s['name'], system=s['system'], power=s['power'])
    
    if not Pokemon.objects.exists():
        print('init pokemons')
        for p in pokemons:
            Pokemon.objects.create(
                name=p['name'],
                no=p['no'],
                system=p['system'],
                attack=p['attack'],
                defense=p['defense'],
                hp=p['hp'],
            )
        
        for p in pokemons:
            evo_no = p['evo_no']
            if not evo_no:
                continue
            p1 = Pokemon.objects.get(no=p['no'])
            p2 = Pokemon.objects.get(no=evo_no)
            p1.evo_to = p2
            p1.save()
    
    for p in Pokemon.objects.all():
        if not p.evo_to:
            p.level = 20
            p.save()
            continue
        if p.pokemon_set.exists():
            p.level = 10
            p.save()
            continue

