# Generated by Django 2.1.4 on 2019-09-02 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Skill'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(-1, '弃牌'), (0, '牌堆'), (1, '手牌'), (2, '休养'), (3, '上场')], default=0),
        ),
    ]
