# Generated by Django 2.1.4 on 2019-09-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190902_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(-1, '弃牌'), (0, '牌堆'), (1, '手牌'), (2, '上场')], default=0),
        ),
    ]
