# Generated by Django 2.1.4 on 2019-09-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190902_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='winner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wild',
            name='winner',
            field=models.IntegerField(default=0),
        ),
    ]
