# Generated by Django 2.1.4 on 2019-09-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='wild',
            name='events',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='events',
            field=models.TextField(blank=True),
        ),
    ]
