# Generated by Django 2.2.4 on 2019-09-06 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20190904_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='events',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='card1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card1_battle_set', to='game.Card'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='card2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card2_battle_set', to='game.Card'),
        ),
    ]
