# Generated by Django 2.1.4 on 2019-09-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20190906_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='block',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.IntegerField(choices=[(-1, '弃牌'), (0, '牌堆'), (1, '上场'), (2, '休息')], default=0),
        ),
    ]
